// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HelloWorld
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int button1 = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int buttonToNotes = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int frameLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout1 = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout3 = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout4 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int listView1 = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int notesAddButton = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int notesNoteName = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int notesNoteValue = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int textView2 = 2131034118;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Note = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Notes = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
