// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HelloWorld
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int custom_text_size = 2131034112;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Cat = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int buttonToNotes = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int catsButton = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int frameLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout1 = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout3 = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout4 = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int noteListDel = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int noteListName = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int noteListValue = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int notesAddButton = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int notesInfo = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int notesList = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int notesNoteName = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int notesNoteValue = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int textView2 = 2131099662;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Note = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Notes = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
